### ISSUE TITLE
Clean up fta-fmea related repositories

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#132]
For repositories fta-fmea and fta-fmea-ui:
- remove all non-active branches or propose what to do with it
- revise all security bumps from github

**Comment by blcham** [comment]
Branches:
- avic -- we want to keep it to know what was deployed in msmt project

**Comment by kostobog** [comment]
Removed merged branches and "expired" dependabot branches. There are several branches left:
### **FTA-FMEA-UI**
**"Main" branches**
- master - old branch used with gitblit. replaced by main 
- avic

**Active branches**
- feature/persist-fta-diagram-layout - review stage

**Other non-merged branches**
- feature/function-parts - not finished
- feature/system-tree-editor - not finished
- fix/create-and-update-api-calls-with-references - not sure 
- create-FTA-example-from-demo - work in progress, fta-construction-algorithm.md
  	
	
### FTA-FMEA
**"Main" branches**
- master
- avic

**Active branches**
- feature/persist-diagram-layout - to be merged 
	
**Other non-merged branches**
- fix-fmea-generation - not finished
- process-annotations-on-import-document - not finished 
- feature/function-parts - not finished

**Comment by blcham** [comment]
- remove master

**Comment by kostobog** [comment]
@blcham 
Based on the review I investigated the old branches. Some branches were already merged while others had an open pull request. Changes are reflected in the post above.

**Comment by blcham** [comment]
@kostobog good work here!!!
