### ISSUE TITLE
FTA diagram context menu is covered by OS context menu

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#142]

**Comment by LaChope** [comment]
@kostobog @blcham Can I get more context? not sure where to reproduce this issue

**Comment by blcham** [comment]
It is context menu for canvas where FTA tree is shown.

**Comment by LaChope** [comment]
@blcham @kostobog 
Would it be good solution to disable browser context menu in the whole app? Or is it better only in the canvas?

**Comment by blcham** [comment]
It depends how hard it is, for me disabling it in canvas is better if not too hard.
