### ISSUE TITLE
Migrate FTA-FMEA-UI to Vite

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea-ui#151]
A/C:
-
- [x] Work with development server
- [x] Have sourcemap
- [x] Dockerization is working
- [x] Dockerization with environment variables at runtime
- [ ]  Dockerization works while being at a complex path within the application, i.e. having context path of the application `/fta` (e.g. `kbss...../fta/`) or even accessing path `/fta/xxx/yyy`

There is some known "issue": when building with sourcemap, a lot of warnings are displayed (e.g. `node_modules/@mui/material/Paper/Paper.js (1:0) Error when using sourcemap for reporting an error: Can't resolve original location of error.`), but according to [this thread](https://github.com/vitejs/vite/issues/15012), this is not really a problem and should be ignored.

**Comment by LaChope** [comment]
@blcham It is now fully working, also with docker. I just have a question: do we want to have sourcemap in production? I assume it is not necessary as it is not deployed on Netlify or Storybook (for now, sourcemap is active)

**Comment by blcham** [comment]
> @blcham It is now fully working, also with docker. I just have a question: do we want to have sourcemap in production? I assume it is not necessary as it is not deployed on Netlify or Storybook (for now, sourcemap is active)

Fow now i would leave it included there.

**Comment by blcham** [comment]
Currently main issue:
- in "svg-pan-zoom" there is most-likely a function exported as "named function"
- import `import * as svgPanZoom from "svg-pan-zoom";` works with Vite but only in "npm dev" but not in "npm preview", or behind nginx in dockerization
    - other imports of type `import * as ..` seems to work well
    - it throws error svgPanZoom is not a function

To fix it we had [2 options](https://unional.gitbooks.io/typescript/content/pages/06-files-and-projects/compiler-options.html) to configure tsconfig.json:
    - "allowSyntheticDefaultImports": true
        - does not change anything, only allowing for typescript to import CommonJs with the same syntax as you would import ES modules
    - "esModuleInterop": true
        - this is recommended way. It does the same, just on top of that it makes sure that CommonJs module

**Comment by LaChope** [comment]
@blcham FYI I created ticket out of https://github.com/kbss-cvut/fta-fmea-ui/issues/151#issue-2096110684 here: #167
