### ISSUE TITLE
Change style of fault event nodes and their connections in fault tree diagram

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#162]
The style should be changed as follows
- nodes in fault tree should resize to fit label
- reduce space fault event label and fault event box
- resize gates by factor of 0.5

We want to use gate-like symbol to differentiate between nodes.
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/87564f30-f6d1-4034-962b-2aff0cb0aa57)

We want to have a more natural look of lines connecting gates and its sub-nodes:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/29a568c1-a24a-46fa-93a2-74d721a549ac)

A/C:
- all types of FTA nodes (basic, external, immediate) are visualized as rectangles
- types of FTA nodes (basic, external, immediate) are visually differentiated by gate-like symbol below the node
- the rectangle that represents FTA node is automatically resized according to underlying text
- lines connecting gate with its related nodes look more natural

**Comment by blcham** [comment]
I do not recommend implementing 2 variants of displaying nodes in FTA tree, just the variant with full label (we can always implement it later):  
   1) ~~show shortened labels ending with "..."~~
   2) full label mode which would display full labels of all nodes (useful mainly for export)

**Comment by blcham** [comment]
Here are some examples of how FTA trees look-like in different tools (use it for inspiration, mainly to see how gates are connected to sub-nodes):

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/51f31b43-e1c8-4f7f-b394-6f30f5aa7d3b)

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/83259a96-9b6d-4538-8d82-238622733a11)

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/84e3b386-6f72-4bea-86c9-59e5052aa4cd)
