### ISSUE TITLE
Render probability/failure-rate next to right bottom corner of fault event in fault tree diagram

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#163]
@blcham

**Comment by blcham** [comment]
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/730bd868-2651-4bab-a079-e545e097b042)

**Comment by blcham** [comment]
@Kasmadei

**Comment by LaChope** [comment]
Closing as completed in https://github.com/kbss-cvut/fta-fmea-ui/pull/185
