### ISSUE TITLE
Render failure rate requirement at top right corner of Fault Event in fault tree diagram.

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#166]
The fault event node in fault tree diagram should be capable of rendering failure rate requirement as shown in screenshot below.

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/18463762/e8bdc46a-3487-479c-a43a-6d3e40fcc7b9)

1. Extend the `FaultEvent` model by adding a `probabilityRequirement` field
2. src/components/editor/faultTree/shapes/shapesDefinitions.txs - add probabilityRequirementLabel element into `Event` shape and add css to render it at top right corner.
3. src/components/editor/faultTree/shapes/RenderTree - how `FaultTree.probability` is used to set the probability label of a `nodeShape`.

See how FaultEvent.probability is rendered.

The probability requirement label should not be visible if there is no value in the FaultEvent.probabilityRequirement.

**Comment by blcham** [comment]
@Kasmadei

**Comment by Kasmadei** [comment]
Prepared for review: https://github.com/kbss-cvut/fta-fmea-ui/pull/188 @blcham @LaChope

**Comment by LaChope** [comment]
Closing as completed in https://github.com/kbss-cvut/fta-fmea-ui/pull/188
