### ISSUE TITLE
Show clickable fault tree cutsets in fault tree editor sidebar

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#171]
This is how it should look like:
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/db0888fa-4136-438f-b3f6-b87a173a8db2)

A/C:
- cutsets are visualized as a table ordered by priority
- each row of the table should be clickable, while on click, concrete cut-set is highlighted in the FTA tree

**Comment by Kasmadei** [comment]
Agreed with @blcham to close.
