### ISSUE TITLE
Evaluation of fault tree probabilities should take into account multiple occurrences of an event in fault tree

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#174]
Evaluation should be done using the method based on minimal cutsets.
Description of the idea is described in chapter "9.6.2 Metoda miniálných kritiských řezů" [spolehlivost letadlove techniky VUT](https://drive.google.com/file/d/10_3bWuIL6nzwK5XaRP3tAD8Vx7aKSajN/view?usp=drive_link).

#### The algorithm has the following steps:
1. extract minimal cut sets
2. transform the OR of minimal cut sets into Shannon's decomposition and convert it into normal disjunctive form removing contradicting clauses, e.g. clauses containing both an event and its negation.
3. evaluate probability of the output of step 2.

#### Change server side API
- fault tree should not be evaluated when the tree is fetched from the server
- add one new API method to call the evaluation of the fault tree probabilities and extraction of cutsets. The API method should be 
  `PUT /{faultTreeFragment}/evaluate`

### Client Side
- cutest button should call the new evaluate server side API `PUT /{faultTreeFragment}/evaluate`

**Comment by blcham** [comment]
@kostobog should this be closed ?

**Comment by kostobog** [comment]
@blcham the backend side is done. I think the front end is also done but I am not sure.
