### ISSUE TITLE
Set up default reviewers for record-manager-ui and fta-fmea-ui

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea-ui#176]
Just add CODEOWNERS file as described here:
https://stackoverflow.com/questions/46340474/set-a-default-reviewer

- [x] fta-fmea-ui it should be one me, Bogdan, 

- [ ] record-manager-ui it should be one of me, Bogdan, Max

Note in case we decide to set at least one of these repos as private (from [github](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)):

> Important
> 
> You can define code owners in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see "[GitHub’s plans](https://docs.github.com/en/get-started/learning-about-github/githubs-plans)."

**Comment by LaChope** [comment]
@blcham this what not merged in FTA-FMEA-UI, should I merge it?

**Comment by blcham** [comment]
No it does not make sense to me ... we can discuss at standup

**Comment by blcham** [comment]
Irrelevant
