### ISSUE TITLE
Refactor application ontology and related API

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#198]
- [x] Set up convention how to create ontological entities
- [x] Add those convention to ontology documentation (e.g. rdfs:comment)
- [x] Refactor it on backend
- [x] Refactor it on frontend
- [x] Include SPARQL queries here for the refactoring
- [x] Refactor data in fta-fmea-demo
- [ ] Refactor data in fta-fmea-avic  if it makes sense (most-likely it does not)

**Comment by blcham** [comment]
@kostobog

**Comment by blcham** [comment]
Created based-on https://github.com/kbss-cvut/fta-fmea/pull/68#discussion_r1522932971

**Comment by kostobog** [comment]
@blcham Queries for data refactoring based on renamed ontology IRIs can be found in [refactoring.zip](https://github.com/kbss-cvut/fta-fmea-ui/files/14617927/refactoring.zip)

**Comment by kostobog** [comment]
@blcham 
I am not sure how to deploy new version of fta-fmea-ui on kbss via jenkins. fta-fmea-ui requires  node version 20. KBSS has older version.
For more details see jenkins [error log](https://kbss.felk.cvut.cz/jenkins/job/fta-fmea-ui-demo/28/console).


Can we update the node version on KBSS, or can we install another version of node? 
Related issue #168

**Comment by blcham** [comment]
@kostobog should be easy to set up when done with https://github.com/kbss-cvut/fta-fmea-ui/pull/138

**Comment by blcham** [comment]
Last two points from the issues description are not resolved yet.

**Comment by kostobog** [comment]
@blcham 
data in fta-fmea-demo is refactored. Not uploading here. It will be included in the new fta-fmea-demo docker deployment at kbss.

**Comment by kostobog** [comment]
@blcham 
In my opinion it is not necessary to do the refactoring of data in AVIC deployment now.
