### ISSUE TITLE
FTA root node does not show any probabilities

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#212]
I used deploy/internal-auth deployment to see the FTA tree as follows:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/3d6c7598-a4c2-4d05-aada-a317595b5ce0)

I expected to see:
- [ ] root node computed probability
- [ ] required probability

None of those are shown within the UI.
@Kasmadei, please investigate where the issue is. If a backend issue is found assign the ticket to @kostobog.

**Comment by blcham** [comment]
FYI, here is a related issue -- https://github.com/kbss-cvut/fta-fmea-ui/issues/212

**Comment by Kasmadei** [comment]
> FYI, here is a related issue -- [#212](https://github.com/kbss-cvut/fta-fmea-ui/issues/212)
> 
> Note from [@kostobog](https://github.com/kostobog): In order to compute cutsets, please use **only** request `PUT .../fault-tree/$fragment/evaluate` (if you are not doing so)

Yes, previous endpoint was wrong, changed it already (locally)

**Comment by Kasmadei** [comment]
``` "supertypes": [
            {
                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event-type/instance833438683",
                "@type": [
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event-type"
                ],
                "name": "FC_1.1. Tlak v kabině fault event",
                "failureRate": {
                    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate/instance1752675736",
                    "@type": [
                        "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate"
                    ],
                    "requirement": {
                        "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate-requirement/instance-1318429931",
                        "@type": [
                            "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate-requirement"
                        ],
                        "upperBound": 4.0E-4
                    }
                },
                "triggeredBySituations": [],
                "bringsAboutSituations": []
            }
        ], ```
