### ISSUE TITLE
Language translations are not working when basename is defined

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#213]
If `FTA_FMEA_BASENAME` is different from `""`,  i18n does not work. By default as explained in https://github.com/kbss-cvut/fta-fmea-ui/blob/48b650ba35bcd561d1ad6bb5dc1d5e5c64f1610b/deploy/internal-auth/.env#L4 is `FTA_FMEA_BASENAME=/fta-fmea`, thus it can be tested in internal-auth deployment.

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/273d22ec-5ed4-4a31-a0f4-872096990214)

------

A/C:
- UI shows czech/english labels based on selection of language of UI

**Comment by Kasmadei** [comment]
https://github.com/kbss-cvut/fta-fmea-ui/blob/48b650ba35bcd561d1ad6bb5dc1d5e5c64f1610b/src/components/routes/AppRoutes.tsx#L27
