### ISSUE TITLE
Add properties related to root node and SNS node

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#226]
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/eaf9b523-bda6-47a5-9214-7fdfb992d664)
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/1afb6c78-22dd-4f35-b57f-71f6ffe3c561)

To show it in UI you should have data in internal-auth deployment. Moreover, consider commenting on Figma for issues related to design.

A/C:
- all properties that cannot be shown because there are no data available should be reported (ASAP)
- all properties that are gray should be in UI read-only

**Comment by Kasmadei** [comment]
@blcham  Here is the example of tree that i get from server side (GET http://localhost:1235/fta-fmea/services/fta-fmea-server/faultTrees/instance1443295929). And i am not sure if i can use some properties for task except **probability** and **upperBound** Mb i don't see something ? 
{
    "@context": {
        "types": "@type",
        "upperBound": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/to",
        "probability": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/probability",
        "description": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/description",
        "bringsAboutSituations": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/is-bringing-about",
        "eventType": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event-type",
        "requirement": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/has-requirement",
        "uri": "@id",
        "failureRate": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/has-failure-rate",
        "childrenSequence": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/has-child-sequence",
        "children": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/has-child",
        "name": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/name",
        "x": "http://onto.fel.cvut.cz/ontologies/diagram/x",
        "width": "http://onto.fel.cvut.cz/ontologies/diagram/width",
        "prediction": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/has-prediction",
        "isReference": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/is-reference",
        "y": "http://onto.fel.cvut.cz/ontologies/diagram/y",
        "rectangle": "http://onto.fel.cvut.cz/ontologies/diagram/has-rectangle",
        "gateType": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/gate-type",
        "manifestingEvent": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/is-manifested-by",
        "triggeredBySituations": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/is-triggered-by",
        "value": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/value",
        "height": "http://onto.fel.cvut.cz/ontologies/diagram/height",
        "supertypes": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/is-derived-from"
    },
    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-tree/instance1443295929",
    "types": [
        "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-tree"
    ],
    "name": "FC 1.1. Tlak v kabině fault event",
    "manifestingEvent": {
        "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance1811035853",
        "types": [
            "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
            "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event"
        ],
        "gateType": "OR",
        "isReference": false,
        "name": "FC 1.1. Tlak v kabině fault event",
        "eventType": "INTERMEDIATE",
        "description": "",
        "probability": 6.250554136100206E-5,
        "rectangle": {
            "uri": "http://onto.fel.cvut.cz/ontologies/diagram/rectangle/instance720425674",
            "types": [
                "http://onto.fel.cvut.cz/ontologies/diagram/rectangle"
            ],
            "y": 0.0,
            "x": 280.0,
            "width": 100.0,
            "height": 100.0
        },
        "childrenSequence": {
            "@list": [
                {
                    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance-741532472"
                },
                {
                    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance820186229"
                },
                {
                    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance621415126"
                },
                {
                    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance1369205353"
                },
                {
                    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance-650995087"
                }
            ]
        },
        "bringsAboutSituations": [],
        "children": [
            {
                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance-741532472",
                "types": [
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event"
                ],
                "isReference": false,
                "name": "21-30-00 - Pressurization control",
                "eventType": "BASIC",
                "description": "",
                "probability": 1.667E-5,
                "rectangle": {
                    "uri": "http://onto.fel.cvut.cz/ontologies/diagram/rectangle/instance-439695733",
                    "types": [
                        "http://onto.fel.cvut.cz/ontologies/diagram/rectangle"
                    ],
                    "y": 190.0,
                    "x": 110.0,
                    "width": 80.0,
                    "height": 80.0
                },
                "childrenSequence": {
                    "@list": []
                },
                "bringsAboutSituations": [],
                "children": [],
                "triggeredBySituations": []
            },
            {
                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance820186229",
                "types": [
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event"
                ],
                "isReference": false,
                "name": "21-30-01 (pn-11) - Regulator Failure",
                "eventType": "BASIC",
                "description": "",
                "probability": 1.6667E-5,
                "rectangle": {
                    "uri": "http://onto.fel.cvut.cz/ontologies/diagram/rectangle/instance-421231482",
                    "types": [
                        "http://onto.fel.cvut.cz/ontologies/diagram/rectangle"
                    ],
                    "y": 190.0,
                    "x": 260.0,
                    "width": 80.0,
                    "height": 80.0
                },
                "childrenSequence": {
                    "@list": []
                },
                "bringsAboutSituations": [],
                "children": [],
                "supertypes": [
                    {
                        "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event-type/instance-2004562549",
                        "types": [
                            "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                            "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event-type"
                        ],
                        "name": "pn-11 fails",
                        "failureRate": {
                            "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate/instance-598535435",
                            "types": [
                                "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate"
                            ],
                            "prediction": {
                                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate-estimate/instance143740879",
                                "types": [
                                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/analysis-product",
                                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate-estimate"
                                ],
                                "value": 0.005
                            }
                        },
                        "triggeredBySituations": [],
                        "bringsAboutSituations": []
                    }
                ],
                "triggeredBySituations": []
            },
            {
                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance-650995087",
                "types": [
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event"
                ],
                "isReference": false,
                "name": "21-30-03 (pn-13) - Control and safety valve Failure",
                "eventType": "BASIC",
                "description": "",
                "probability": 1.667E-5,
                "rectangle": {
                    "uri": "http://onto.fel.cvut.cz/ontologies/diagram/rectangle/instance1945453232",
                    "types": [
                        "http://onto.fel.cvut.cz/ontologies/diagram/rectangle"
                    ],
                    "y": 180.0,
                    "x": 550.0,
                    "width": 80.0,
                    "height": 80.0
                },
                "childrenSequence": {
                    "@list": []
                },
                "bringsAboutSituations": [],
                "children": [],
                "supertypes": [
                    {
                        "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event-type/instance-747419011",
                        "types": [
                            "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                            "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event-type"
                        ],
                        "name": "pn-13 fails",
                        "failureRate": {
                            "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate/instance923379609",
                            "types": [
                                "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate"
                            ],
                            "prediction": {
                                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate-estimate/instance-1465258761",
                                "types": [
                                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/analysis-product",
                                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate-estimate"
                                ],
                                "value": 0.005
                            }
                        },
                        "triggeredBySituations": [],
                        "bringsAboutSituations": []
                    }
                ],
                "triggeredBySituations": []
            },
            {
                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance621415126",
                "types": [
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event"
                ],
                "isReference": false,
                "name": "21-30-02 (pn-12) - Control valve Failure",
                "eventType": "BASIC",
                "description": "",
                "probability": 1.25E-5,
                "rectangle": {
                    "uri": "http://onto.fel.cvut.cz/ontologies/diagram/rectangle/instance429145967",
                    "types": [
                        "http://onto.fel.cvut.cz/ontologies/diagram/rectangle"
                    ],
                    "y": 180.0,
                    "x": 390.0,
                    "width": 80.0,
                    "height": 80.0
                },
                "childrenSequence": {
                    "@list": []
                },
                "bringsAboutSituations": [],
                "children": [],
                "supertypes": [
                    {
                        "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event-type/instance-147780273",
                        "types": [
                            "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                            "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event-type"
                        ],
                        "name": "pn-12 fails",
                        "failureRate": {
                            "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate/instance319961958",
                            "types": [
                                "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate"
                            ],
                            "prediction": {
                                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate-estimate/instance-1463970910",
                                "types": [
                                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/analysis-product",
                                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate-estimate"
                                ],
                                "value": 0.006
                            }
                        },
                        "triggeredBySituations": [],
                        "bringsAboutSituations": []
                    }
                ],
                "triggeredBySituations": []
            }
        ],
        "supertypes": [
            {
                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event-type/instance833438683",
                "types": [
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event-type"
                ],
                "name": "FC_1.1. Tlak v kabině fault event",
                "failureRate": {
                    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate/instance1752675736",
                    "types": [
                        "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate"
                    ],
                    "requirement": {
                        "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate-requirement/instance-1318429931",
                        "types": [
                            "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/failure-rate-requirement"
                        ],
                        "upperBound": 4.0E-4
                    }
                },
                "triggeredBySituations": [],
                "bringsAboutSituations": []
            }
        ],
        "triggeredBySituations": []
    }
}

**Comment by blcham** [comment]
@kostobog

**Comment by blcham** [comment]
accidentally closed.

**Comment by blcham** [comment]
@Kasmadei some of the issues were solved in https://github.com/kbss-cvut/fta-fmea-ui/pull/243

**Comment by kostobog** [comment]
I added missing properties to example, see PR #243.
Also fixed reading the fault tree and fault events in PR kbss-cvut/fta-fmea#78

**Comment by Kasmadei** [comment]
@kostobog Hi, is it correct example ?

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/49252228/7d2f9266-1e06-4d89-8e1f-152f2ea2f387)

Looks like i don't have any new props. Here is my server response: 



{
    "@context": {
        "types": "@type",
        "probability": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/probability",
        "description": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/description",
        "bringsAboutSituations": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/is-bringing-about",
        "eventType": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event-type",
        "uri": "@id",
        "childrenSequence": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/has-child-sequence",
        "children": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/has-child",
        "name": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/name",
        "x": "http://onto.fel.cvut.cz/ontologies/diagram/x",
        "width": "http://onto.fel.cvut.cz/ontologies/diagram/width",
        "isReference": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/is-reference",
        "y": "http://onto.fel.cvut.cz/ontologies/diagram/y",
        "rectangle": "http://onto.fel.cvut.cz/ontologies/diagram/has-rectangle",
        "gateType": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/gate-type",
        "manifestingEvent": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/is-manifested-by",
        "triggeredBySituations": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/is-triggered-by",
        "height": "http://onto.fel.cvut.cz/ontologies/diagram/height"
    },
    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-tree/instance1443295929",
    "types": [
        "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-tree"
    ],
    "name": "FC 1.1. Tlak v kabině fault event",
    "manifestingEvent": {
        "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance1811035853",
        "types": [
            "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
            "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event"
        ],
        "gateType": "OR",
        "isReference": false,
        "name": "FC 1.1. Tlak v kabině fault event",
        "eventType": "INTERMEDIATE",
        "description": "",
        "rectangle": {
            "uri": "http://onto.fel.cvut.cz/ontologies/diagram/rectangle/instance720425674",
            "types": [
                "http://onto.fel.cvut.cz/ontologies/diagram/rectangle"
            ],
            "y": 0.0,
            "x": 280.0,
            "width": 100.0,
            "height": 100.0
        },
        "childrenSequence": {
            "@list": [
                {
                    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance-741532472"
                },
                {
                    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance820186229"
                },
                {
                    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance621415126"
                },
                {
                    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance1369205353"
                },
                {
                    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance-650995087"
                },
                {
                    "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance1204570762"
                }
            ]
        },
        "bringsAboutSituations": [],
        "children": [
            {
                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance-741532472",
                "types": [
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event"
                ],
                "isReference": false,
                "name": "21-30-00 - Pressurization control",
                "eventType": "BASIC",
                "description": "",
                "probability": 1.667E-5,
                "rectangle": {
                    "uri": "http://onto.fel.cvut.cz/ontologies/diagram/rectangle/instance-439695733",
                    "types": [
                        "http://onto.fel.cvut.cz/ontologies/diagram/rectangle"
                    ],
                    "y": 190.0,
                    "x": 110.0,
                    "width": 80.0,
                    "height": 80.0
                },
                "childrenSequence": {
                    "@list": []
                },
                "bringsAboutSituations": [],
                "children": [],
                "triggeredBySituations": []
            },
            {
                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance1204570762",
                "types": [
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event"
                ],
                "isReference": false,
                "name": "FC_1.3. Tlak v kabině fault event",
                "eventType": "EXTERNAL",
                "description": "",
                "probability": 0.1,
                "rectangle": {
                    "uri": "http://onto.fel.cvut.cz/ontologies/diagram/rectangle/instance1338098093",
                    "types": [
                        "http://onto.fel.cvut.cz/ontologies/diagram/rectangle"
                    ],
                    "y": 180.0,
                    "x": 700.0,
                    "width": 100.0,
                    "height": 100.0
                },
                "childrenSequence": {
                    "@list": []
                },
                "bringsAboutSituations": [],
                "children": [],
                "triggeredBySituations": []
            },
            {
                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance820186229",
                "types": [
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event"
                ],
                "isReference": false,
                "name": "21-30-01 (pn-11) - Regulator Failure",
                "eventType": "BASIC",
                "description": "",
                "probability": 1.6667E-5,
                "rectangle": {
                    "uri": "http://onto.fel.cvut.cz/ontologies/diagram/rectangle/instance-421231482",
                    "types": [
                        "http://onto.fel.cvut.cz/ontologies/diagram/rectangle"
                    ],
                    "y": 190.0,
                    "x": 260.0,
                    "width": 80.0,
                    "height": 80.0
                },
                "childrenSequence": {
                    "@list": []
                },
                "bringsAboutSituations": [],
                "children": [],
                "triggeredBySituations": []
            },
            {
                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance-650995087",
                "types": [
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event"
                ],
                "isReference": false,
                "name": "21-30-03 (pn-13) - Control and safety valve Failure",
                "eventType": "BASIC",
                "description": "",
                "probability": 1.667E-5,
                "rectangle": {
                    "uri": "http://onto.fel.cvut.cz/ontologies/diagram/rectangle/instance1945453232",
                    "types": [
                        "http://onto.fel.cvut.cz/ontologies/diagram/rectangle"
                    ],
                    "y": 180.0,
                    "x": 550.0,
                    "width": 80.0,
                    "height": 80.0
                },
                "childrenSequence": {
                    "@list": []
                },
                "bringsAboutSituations": [],
                "children": [],
                "triggeredBySituations": []
            },
            {
                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance621415126",
                "types": [
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event"
                ],
                "isReference": false,
                "name": "21-30-02 (pn-12) - Control valve Failure",
                "eventType": "BASIC",
                "description": "",
                "probability": 1.25E-5,
                "rectangle": {
                    "uri": "http://onto.fel.cvut.cz/ontologies/diagram/rectangle/instance429145967",
                    "types": [
                        "http://onto.fel.cvut.cz/ontologies/diagram/rectangle"
                    ],
                    "y": 180.0,
                    "x": 390.0,
                    "width": 80.0,
                    "height": 80.0
                },
                "childrenSequence": {
                    "@list": []
                },
                "bringsAboutSituations": [],
                "children": [],
                "triggeredBySituations": []
            }
        ],
        "triggeredBySituations": []
    }
}

**Comment by kostobog** [comment]
@blcham @Kasmadei
This should be working now. Here is the JSON-LD  [response with the fault tree](https://github.com/kbss-cvut/fta-fmea-ui/files/14951081/fault-tree.json)  returned from the backend in the latest docker image. 

I fixed two issues to make it work.
-  issue with the backend - lazy loading of relationships was not working. This is resolved by wrapping reading the fault tree in a transaction to enable lazy loading of relationships to other entities, see kbss-cvut/fta-fmea#79
- issue with the example data - the new sns-partonomy-example--anonymized.ttl was committed without an ontology triple which prevented loading it into db-server. Fixed in 64b5b486361b04dd9ba6b1762fb47fbe5403b1fe

**Comment by Kasmadei** [comment]
@kostobog I have updated BE. Used docker compose pull, cleared DB + repo sync, but unfortunately i don't see any changes :( Can you explain pls how am I supposed to update the server?

**Comment by kostobog** [comment]
@Kasmadei 
That is strange, it works for me. I tested it both running from IDE as well and docker. 

This is my Docker setup:
- go to in `deploy/internal-auth/
- `docker-compose pull`
- if internal-auth deployment is running run `docker-compose down`
- run `docker-compose up`

If this does not work, try to delete the containers and volumes associated with the `internal-auth` deployment and run `docker-compose up`

**Comment by blcham** [comment]
@kostobog I updated your steps, please:
- confirm it makes sense to you
- add last steps to ensure that it works (something like, call "register and login as user", "call /evaluate", cal "/fta-tree/xxx` and make sure that it returned something ...

**Comment by Kasmadei** [comment]
@kostobog Thank you, it works!

**Comment by kostobog** [comment]
@Kasmadei 
- [**optional**] `criticality` = `severity` - it will appear only for root nodes (root node is INTERMEDIATE) and EXTERNAL reference event. 
- [**optional**] `prediction.value` = `predicted failure rate` for leaf node and =`FHA based failure rate` for root node 
  - there is missing data to distinguish failure rate prediction from failure rate estimate. 
- [**optional**] `ataCode` + `name`= `ATA System` for root and External reference nodes and `Component type` for leaf events - the full path for both ataCode and name is `supertypes[i].behavior.item.supertypes[j].ataCode`. You have to find indexes `i` and `j` where the ataCode property is present. 
  - Additionally there it should hold that `item.types` contains `.../sns-component` and `item.supertypes[j].types` contains '.../ata-system'. For now `i` is probably always 0 because the array is of length 1, but there could be at least to possible values for `0<=j<2`.
You should also get the following properties:
- `partNumber` and  `stock` - should be there also in supertypes[i].behavior.item[j] for some `i` and `j`. 
Try to delete docker container and volume then pull and compose up. 

The following properties are not important for now:
- failureModeType and behaviorType  


The property `item.quantity`  is missing. This is due to incorrect fault tree example. I will try to fix it tomorrow.

**Comment by Kasmadei** [comment]
@kostobog Hi, i wanted to ask about help with "ATA System". As u know after endpoint (/fta-fmea/services/fta-fmea-server/faultTrees/instance1443295929) call, FE also call JsonLdUtils.compactAndResolveReferences<FaultTree>(response.data, CONTEXT); function that transforms JSON. In a CONTEXT i added:

criticality: VocabularyUtils.PREFIX + "criticality",
and
behavior: VocabularyUtils.PREFIX + "behavior",

But for some reason i am not able too se "behavior" prop after transformation. Here is part of object after transformation: 

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/49252228/5f60826e-fbe3-472a-b8c2-bbc2e8b10354)

I can't figure out what I'm doing wrong. Don't have enough experience working with context :(

**Comment by Kasmadei** [comment]
@kostobog Can you please check this small PR: https://github.com/kbss-cvut/fta-fmea-ui/pull/251/files

**Comment by blcham** [comment]
@Kasmadei next time i suggest to not reference uri $PR/files, because this way this issue is not connected to the PR  (i.e. you will not see link from the PR to this issue, which is not good because person trying to close PRs might not be able to find this connection)

Thus, use https://github.com/kbss-cvut/fta-fmea-ui/pull/251 instead.

**Comment by kostobog** [comment]
@Kasmadei Hi,
I checked PR #251. I think the context for `behavior` is wrong. This should be the correct one:
- behavior: VocabularyUtils.PREFIX + "is-manifestation-of" - see comment in #251.

To extend the context correctly check the context in the response, e.g. `"behavior": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/is-manifestation-of"`.

I merged #253 which adds `quantity` property and fixes some issues with the example.

**Comment by Kasmadei** [comment]
> [@Kasmadei](https://github.com/Kasmadei), next time, I suggest not referencing uri $PR/files but rather PR directly (i.e., without "/files" suffix) .
> 
> It is because your link does not connect PR to this issue (i.e. you will not see link from the PR to this issue, which is not good for a person trying to close open PRs as he might not be able to find out what is the PR about -- description of the PR is not there which is not the problem if linked to this issue)
> 
> Thus, use [#251](https://github.com/kbss-cvut/fta-fmea-ui/pull/251) instead.

Thanks, didn't know about it :)

**Comment by Kasmadei** [comment]
PR: https://github.com/kbss-cvut/fta-fmea-ui/pull/256
