### ISSUE TITLE
Implement hints for FTA node properties

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#227]
For properties of FTA nodes we have many hints as can be seen here: 
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/1996d80f-ae3e-497e-9005-af0b3d2f47fb)

The goal of this issue is to implement "a help/hint component" that would be next to the label of the property and on hover it would show a description of the property.

A/C:
- hint should be implemented as a separate component
- all hints related to FTA nodes shown in Figma should be implemented and translated using i18n
- there should be a convention on how to name i18n key so it is clear that it is a hint explaining some RDF property

**Comment by blcham** [comment]
@kostobog currently it is not working at KBSS, please check

**Comment by kostobog** [comment]
@blcham
PR #228 resolving this issue only introduces a HintText component and translation. The PR does not apply the hints to the properties. Also I could not find a version/commit where HintText was applied to node properties.
