### ISSUE TITLE
Calculate cutset path does not return cutsets

### ISSUE THREAD

**Issue by Kasmadei** [kbss-cvut/fta-fmea-ui#236]
From now for some reason i don't see any result after "evaluate" endpoint call: 

**curl** 'http://localhost:1235/fta-fmea/services/fta-fmea-server/faultTrees/instance1443295929/evaluate' \
  -X 'PUT' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,cs;q=0.8,de;q=0.7,ru;q=0.6,uk;q=0.5,zh-TW;q=0.4,zh;q=0.3,hi;q=0.2' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXNtYWRlaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3MTI0MDU3NjcsImV4cCI6MTcxMjQzNDU2N30.tJGqAEqfLSolTvp1yQhTP7j0Q5VCy_iMs1kCQ7hI7w7NIjA5RyOBXc0hv_8TNW-PJLSeiMXPoSjGbCafs9eFvA' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Origin: http://localhost:5173' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:5173/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"'
<img width="1440" alt="Screenshot 2024-04-06 at 4 53 28 PM" src="https://github.com/kbss-cvut/fta-fmea-ui/assets/49252228/da3c55d2-0a07-4123-a279-f8650d1704ca">

**Comment by blcham** [comment]
not correctly formulated
