### ISSUE TITLE
Implement global switch of a system

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#249]
Relates to following screens:
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/aae455e9-c900-46a7-a481-ba85f83134ce)

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/4443f8d7-b139-4d7d-91fb-a7d37c56bc22)

A/C:
- [x] global selector of system type is implemented
- [x] within the selector, all systems will be possible to select
- [ ] the selector is visible on all screens
- [ ] it should be possible to have different aircraft types selected in different tabs of the browser
- [ ] implementation is compliant with design mentioned [here](https://github.com/kbss-cvut/23ava-distribution/issues/53#issuecomment-2049336776)

**Comment by blcham** [comment]
- work only on list (if not easy to do it in tiles, then hide tiles)

**Comment by Kasmadei** [comment]
@blcham 
Mostly done: https://github.com/kbss-cvut/fta-fmea-ui/pull/277
Need to fix BE to finish logic with trees

**Comment by Kasmadei** [comment]
Updated. Done. https://github.com/kbss-cvut/fta-fmea-ui/pull/277

**Comment by blcham** [comment]
@Kasmadei I found the following issues:

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/a0851962-4fa3-4e46-9c34-450fda8686da)

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/a939d84d-2967-4d51-bb41-a9f3b490115c)

**Comment by blcham** [comment]
@Kasmadei please look at A/C and tick those that are implemented
