### ISSUE TITLE
Implement properties of types of FTA nodes

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#281]
- root node:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/ab16525e-78d0-4c38-93f3-fd5204756288)

- reference external node:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/b64ea891-f818-4fd6-b760-48c28e5c9fab)

- intermediate node:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/2ef33329-6501-4b57-bba9-22577670179a)

- sns node:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/fc0a1baa-dd18-49ec-b70e-14f0a12ca77c)
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/7834768d-0730-4b01-9543-04ebad1a3315)
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/b97b24cd-596c-44d4-9eea-8412fc72ae25)

- external node:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/3a8e1d99-9dec-4e4d-abc1-9763af8f82a2)

@Kasmadei Please investigate first to identify missing data and API methods on backend.

A/C:
- all types of nodes (i.e., root-node, external-node, referenced-node, sns-node, internal-node) are implemented as described in figma
- fields that are in Figma but not implemented are described

**Comment by blcham** [comment]
@grotskat please change disabled property

**Comment by grotskat** [comment]
@blcham changed

**Comment by blcham** [comment]
"Manually defined failure rate" -- should be editable.

**Comment by blcham** [comment]
@grotskat could you write here which "failure rates" should be editable? I am not sure it is clear from those pictures.

**Comment by blcham** [comment]
@kostobog please check that we have API and data

**Comment by blcham** [comment]
@kostobog write about not preserving manual value

**Comment by Kasmadei** [comment]
@kostobog Hi, looks like there is not enough props in sns (Basic) node. Can we add it in my example tree ?

**Comment by Kasmadei** [comment]
@kostobog Hi, can we do some short separate meet about few props from this task again, please ? It would be highly appreciated. Will you have 30-45 min tomorrow (27.05) ?

**Comment by Kasmadei** [comment]
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/49252228/4954e750-b743-495a-8f8a-23f1b3d62945)

**Comment by Kasmadei** [comment]
@blcham I expected to have the missing props in both the basic and external node.

1) Current look of basic event:
```
           {
                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/basic-event",
                "types": [
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/named-entity",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/managed-entity"
                ],
                "eventType": "BASIC",
                "description": "",
                "probability": 0.1,
                "isReference": false,
                "name": "basic event",
                "rectangle": {
                    "uri": "http://onto.fel.cvut.cz/ontologies/diagram/rectangle/basic-event-rect",
                    "types": [
                        "http://onto.fel.cvut.cz/ontologies/diagram/rectangle"
                    ],
                    "y": 220.0,
                    "x": 830.0,
                    "width": 100.0,
                    "height": 110.0
                },
                "bringsAboutSituations": [],
                "supertypes": [],
                "contextEvents": [],
                "childrenSequence": {
                    "@list": []
                },
                "children": [],
                "triggeredBySituations": []
            }
```
2) And external event:
```
            {
                "uri": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/external-event",
                "types": [
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/named-entity",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event",
                    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/managed-entity"
                ],
                "eventType": "EXTERNAL",
                "description": "",
                "probability": 0.1,
                "isReference": false,
                "name": "external event",
                "rectangle": {
                    "uri": "http://onto.fel.cvut.cz/ontologies/diagram/rectangle/external-event-rect",
                    "types": [
                        "http://onto.fel.cvut.cz/ontologies/diagram/rectangle"
                    ],
                    "y": 220.0,
                    "x": 970.0,
                    "width": 100.0,
                    "height": 110.0
                },
                "bringsAboutSituations": [],
                "supertypes": [],
                "contextEvents": [],
                "childrenSequence": {
                    "@list": []
                },
                "children": [],
                "triggeredBySituations": []
            },
```



![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/49252228/75f03701-4341-4800-8705-8f8e1049a3fd)

**Comment by blcham** [comment]
@Kasmadei as I mentioned on last meeting you need to look at SNS node not basic event node.

**Comment by blcham** [comment]
With @Kasmadei, we created a query to retrieve all different kinds of failure rates:
```
PREFIX :   <http://onto.fel.cvut.cz/ontologies/fta-fmea-application/>

SELECT ?faultEvent ?name 
?selectedFailureRateValue ?selectedFailureRateEstimation  
?operationalFailureRateValue ?operationalFailureRateEstimate
?predictedFailureRateValue ?predictedFailureRateEstimate 
?requiredFailureRateValue ?requiredFailureRateEstimate

WHERE {
    
  ?faultEvent a :fault-event .  
  ?faultEvent :name ?name .  
  
  OPTIONAL { 
     ?faultEvent :probability ?selectedFailureRateValue .
  }       

  OPTIONAL { 
     ?faultEvent :has-selected-estimation ?selectedFailureRateEstimation .
  }    
    
  OPTIONAL {
     ?faultEvent :is-derived-from/:has-failure-rate/:has-requirement ?requiredFailureRateEstimate .
     ?requiredFailureRateEstimate :to ?requiredFailureRateValue . 
  }  
  
  OPTIONAL {
     ?faultEvent :is-derived-from/:is-derived-from/:has-failure-rate/:has-estimate ?operationalFailureRateEstimate .
     ?operationalFailureRateEstimate :value ?operationalFailureRateValue . 
  }    
  
  OPTIONAL {
     ?faultEvent :is-derived-from/:is-derived-from/:has-failure-rate/:has-prediction ?predictedFailureRateEstimate .
     ?predictedFailureRateEstimate :value ?predictedFailureRateValue . 
  }                     
}
```

**Comment by blcham** [comment]
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/5616fdaa-3055-4513-b1b0-e7dbcf846f86)

**Comment by blcham** [comment]
@Kasmadei  (@kostobog)

In the end, I decided to implement a `Manually-defined failure rate` without defining a specific object for it. The implication of my decision is that we will not be able to keep `manually-defined failure rate` while switching different types of failure rates.

**Comment by blcham** [comment]
@Kasmadei 

I prepared new query to get the failure rates:
```
PREFIX :   <http://onto.fel.cvut.cz/ontologies/fta-fmea-application/>

SELECT ?faultEvent ?name 
?selectedFailureRateValue ?selectedFailureRateEstimation  
?predictedFailureRateValue ?predictedFailureRateEstimate 
?operationalFailureRateValue ?operationalFailureRateEstimate
?requiredFailureRateValue ?requiredFailureRateEstimate
?superType1 ?superType2
WHERE {
    
  ?faultEvent a :fault-event .  
  ?faultEvent :name ?name .  
  
  OPTIONAL { 
     ?faultEvent :probability ?selectedFailureRateValue .
  }       

  OPTIONAL { 
     ?faultEvent :has-selected-estimation ?selectedFailureRateEstimation .
  }    
    
  OPTIONAL {
     ?faultEvent :is-derived-from/:has-failure-rate/:has-requirement ?requiredFailureRateEstimate .
     ?requiredFailureRateEstimate :to ?requiredFailureRateValue . 
  }  
  
  OPTIONAL {
     ?faultEvent :is-derived-from/:is-derived-from/:has-failure-rate/:has-prediction ?predictedFailureRateEstimate .
     ?predictedFailureRateEstimate :value ?predictedFailureRateValue . 
  }                       
  
  OPTIONAL {
     ?faultEvent :is-derived-from/:is-derived-from/:has-failure-rate/:has-estimate ?operationalFailureRateEstimate .
     ?operationalFailureRateEstimate :value ?operationalFailureRateValue . 
  }    
                         
  ?faultEvent :is-derived-from ?superType1 .
  ?superType1 :is-derived-from ?superType2 .
  ?superType2 :has-failure-rate ?fr .   
}
```

Here is the output:

**Comment by blcham** [comment]
Adding operational failure rate as well: 
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/2bf1cdbf-6441-4ce1-a9a0-b4d0a12cdae2)

**Comment by blcham** [comment]
Current issues found:
- update FaultEvent.probability
- hitting cutset did not show cutsets
- root node shows (m)

**Comment by Kasmadei** [comment]
Points that i have finished:
* [x] External node does not have editable manualy-defined failure rate
* [x] Manually-defined failure rate does not have value in basic node
* [x] I saw twice predicted failure rate
* [x] again there is "Based failure rate" instead of "FHA based failure rate" (it sould be same value as elsewhere, not duplicating twice the string)
* [x] there are no translation for failure rates
* [x] read-only, disabled and other values are not according to Implement properties of types of FTA nodes #281 (comment)


Also for now i hide a fail rate type (like M, O, P) because it will take some time to implement, i'll do it as my next task.

**Comment by blcham** [comment]
Reopening, as no all issues are resolved here

**Comment by blcham** [comment]
@Kasmadei, I reopened the issue as I do not see that the last 2 points would be resolved, are they?
- Failure of 21-30-01 Regularor backend does not return selectedEstimate
- External nodes shows radio button

**Comment by Kasmadei** [comment]
@blcham I have checked both points and can confirm that both of them have already been fixed. I think we can close this one.
