### ISSUE TITLE
Check functionality of new node creation.

### ISSUE THREAD

**Issue by Kasmadei** [kbss-cvut/fta-fmea-ui#297]
In some cases there is impossible to create new nodes (BASIC/EXTERNAL). 
Need to check and fix if possible.

More info will be added after some investigation

**Comment by Kasmadei** [comment]
For now it is impossible to create event node of any type :(

**Comment by blcham** [comment]
@LaChope it should work right?

**Comment by blcham** [comment]
Closing as many issues related to node creation were solved and this issue is too vague.
