### ISSUE TITLE
Fix stock property as it was moved in model

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#299]
This issue is blocked by:
- [x] data example (https://github.com/kbss-cvut/fta-fmea-ui/pull/301)
- [x] backend implementation (https://github.com/kbss-cvut/fta-fmea/pull/99)

**Comment by blcham** [comment]
@Kasmadei, everything is prepared for the implementation

**Comment by Kasmadei** [comment]
Resolved in: https://github.com/kbss-cvut/fta-fmea-ui/pull/330
