### ISSUE TITLE
Implement minimum operational hours

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea-ui#310]
Design decisions are described in: https://github.com/kbss-cvut/fta-fmea-ui/issues/381

Steps:
- [x] implement frontend
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/57750426/835ae0e6-e5c4-4277-ad7e-a95fec34304c)

- [x] implement backend to support it and connect it to frontend
- [x] implement computation with min. operational hours 

A/C:
- it is possible to change the min. operation hours and compute with it probabilities of the current FTA tree
- user should be notified if he has referenced nodes with different min. operational hours
- default min. operation hour is specified during deployment

**Comment by blcham** [comment]
Note that we discussed a button to refresh all "Operational failure rates" of FTA tree

**Comment by blcham** [comment]
@grotskat  update figma

**Comment by blcham** [comment]
For computation of operational failure rate we would have enviroment variable e.g.:
`OPERATIONAL_FAILURE_RATE_SERVICE=http://ava-analytics-sever?component=$componentId`

**Comment by grotskat** [comment]
> [@grotskat](https://github.com/grotskat) update figma

@blcham @kostobog 

I switched tools and options.
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/25af220e-409b-4a60-9b54-25d9544dcd23)


And I changed description of play button.
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/afca4814-2380-4b54-b60e-7fe3a0d57e68)

**Comment by blcham** [comment]
Related design document: https://github.com/kbss-cvut/fta-fmea-ui/issues/381

**Comment by blcham** [comment]
A/C not satisfied yet

**Comment by blcham** [comment]
Are A/C satisfied already? (@LaChope @kostobog)

**Comment by kostobog** [comment]
@blcham @LaChope 
The "cutset" button calls evaluate on the backend. I think we decided that "cutset" should only show the cutsets if available.

**Comment by blcham** [comment]
> @blcham @LaChope The "cutset" button calls evaluate on the backend. I think we decided that "cutset" should only show the cutsets if available. In a quick review other A/Cs are completed.

Will be resolved in https://github.com/kbss-cvut/fta-fmea-ui/issues/427
