### ISSUE TITLE
Cannot show info about FTA node

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#316]
Tested on keycloak-auth:

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/e0280723-7231-45b9-8f70-5e93437bfe8c)

**Comment by Kasmadei** [comment]
This one is a bit difficult to resolve, need to discuss with @blcham. As a hot fix we can just hide one component that does crush, because actual fix will take time

**Comment by Kasmadei** [comment]
@LaChope Can I ask you to check this issue please ? It's difficult to resolve because i am not sure how it was working before. I think that problem happened after https://github.com/kbss-cvut/fta-fmea-ui/issues/283

**Comment by LaChope** [comment]
Ok, I'll have a look

**Comment by blcham** [comment]
An workaround was created so the application does not crush -- but most-likely it needs to be reverted: https://github.com/kbss-cvut/fta-fmea-ui/pull/333

**Comment by Kasmadei** [comment]
You can keep going. I was trying to resolve it, but stuck a bit
