### ISSUE TITLE
Fix issues from testing session

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#334]
- [x] #335

- [x] Tab System is not preselected at home screen of the application
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/0e55c3cd-947d-44f5-a9e4-a65e1453e57f)

- [x] Schematic designation is shown even if there is no value present
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/31b4e032-7b1c-4a83-b02f-6439309ab1af)

- [x] Strange label of failure rate
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/40fca869-1753-4246-9524-7dc0bc512f6c)

- [x] Cutset button fails to calculate FTA tree (returns 500 response)
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/647275bd-bc96-41bb-81ef-173fc7e155b8)

- [x] It is not possible to create new FTA tree (returns 500 response)

**Comment by Kasmadei** [comment]
Fix for point 1: https://github.com/kbss-cvut/fta-fmea-ui/pull/337
Fix for point 2: https://github.com/kbss-cvut/fta-fmea-ui/pull/339
Fix for point 3 and 4: https://github.com/kbss-cvut/fta-fmea-ui/pull/338

**Comment by blcham** [comment]
All issues already merged in main.
