### ISSUE TITLE
It is not possible to know which event is a root even or not

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea-ui#348]
@blcham @Kasmadei @kostobog 
In the current state, it is not possible to know if an event is a root event or not

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/57750426/bc3c4da8-cd0b-4b3f-8e4b-f2d6a11d03ba)

**Comment by Kasmadei** [comment]
@LaChope Agree,  especially when we have to work with shape of data (sep. node)

**Comment by LaChope** [comment]
One way to solve this might be to check if a node has parent nodes or not.

**Comment by Kasmadei** [comment]
@LaChope So i don't see a problem here. Already have check for root node. What solution do you expect ? 
<img width="378" alt="Screenshot 2024-06-03 at 4 04 50 PM" src="https://github.com/kbss-cvut/fta-fmea-ui/assets/49252228/e24a56ee-14f9-4db9-85b9-4117c8c6b490">

**Comment by LaChope** [comment]
Ok nice, I just missed that, that's perfect then.

**Comment by LaChope** [comment]
@Kasmadei so it will be enough to resolve #349 ? If yes, I will close this ticket.

**Comment by Kasmadei** [comment]
I was writing in the same time as you :) I think this will be enough to hide dropdown for root event
