### ISSUE TITLE
It should not be possible to edit Root events and external events

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea-ui#349]
@blcham 
When selecting a root event or an external event, we should not be able to edit it.

**NOTE:** Must wait for https://github.com/kbss-cvut/fta-fmea-ui/issues/316 to be completed

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/57750426/f140f799-1550-4de6-9d26-b415bddaf027)

**Comment by Kasmadei** [comment]
Fix: https://github.com/kbss-cvut/fta-fmea-ui/pull/418
