### ISSUE TITLE
Events for creating FTA node are fetched incorrectly

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#350]
When fetching `Events` to create a root node or any other FTA node, we use the wrong API.

It seems that `faultTrees/$ftaTree/reusableEvents` is used but @kostobog  mentioned that different API should be used (something like `/all-fault-events/$systemFragment`)

**Motivation here is to have all relevant events** -- we want to include also `SNS based events` so we would be able to create SNS node. Of course for root FTA node we do not want to choose from `SNS-based events`.

**Comment by blcham** [comment]
@kostobog please fix/add description above.

**Comment by LaChope** [comment]
@blcham If you want I can do this, I know where to update the API

**Comment by blcham** [comment]
- we need IRI of System instead of name

**Comment by LaChope** [comment]
Closing as solved by #355.
