### ISSUE TITLE
It is not possible to update events in fault tree editor

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea-ui#352]
A/C:
- [ ] it is checked that each type of FTA node can be updated
- [ ] it is checked if changing selection of failure rate also works

@blcham @Kasmadei 
It is not possible to update any event in the fault tree editor. The call to API is `PUT http://localhost:1235/services/fta-fmea-server/faultEvents`.

@kostobog Here the error message from backend, I think we faced similar issue for creating new events no?:
```
ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/fta-fmea] threw exception [Request processing failed: cz.cvut.kbss.jsonld.exception.JsonLdDeserializationException: Type mismatch when setting value false on field private boolean cz.cvut.kbss.analysis.model.FaultEvent.isReference.] with root cause 
ff-kauth-demo-fta-fmea-server  | cz.cvut.kbss.jopa.datatype.exception.UnsupportedTypeTransformationException: Cannot transform value false of type class java.lang.Boolean to target type boolean.
```

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/57750426/f2fabdd1-8233-402b-b2aa-5ec5c928e45c)

**Comment by Kasmadei** [comment]
True. Whole part of functionality with node update was not working for some time :/

**Comment by Kasmadei** [comment]
@LaChope @kostobog @blcham  A/C is not checked

**Comment by blcham** [comment]
A/C needs to be confirmed.

**Comment by blcham** [comment]
@Kasmadei please check and close issue if it works

**Comment by Kasmadei** [comment]
@blcham  Looks like point "it is checked that each type of FTA node can be updated" works, but "changing selection of failure" is not. Still see response code 500 :(.

**Comment by Kasmadei** [comment]
@blcham 
Added a small fix. Just added a refreshTree after update (to be able to see changes): https://github.com/kbss-cvut/fta-fmea-ui/pull/413

**Comment by Kasmadei** [comment]
Tested, it works.
