### ISSUE TITLE
Hook for prettier is not triggered on commit

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#362]
@LaChope 

- it works for me
- it works for @kostobog  (after he did `npm install`)
- it works for @LaChope   (after he did `npm install`)
- does not work for @Kasmadei (on `MacOS`)

**Comment by LaChope** [comment]
Doing npm install also runs husky prepare at the same time, this also solved the issue for me. I cannot investigate on MacOS unfortunately.

@Kasmadei if `npm install` can you try to run explicitely `npm run prepare` and then commit to something to check if it works? 

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/57750426/295fb4a7-9e64-4bcf-8420-9555224e313f)

**Comment by LaChope** [comment]
@Kasmadei What was the issue? I have the same problem that it does not work on save, but only on commit.
