### ISSUE TITLE
It is not possible to login or register with internal auth

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea-ui#365]
When using internal auth (both development and production modes), I cannot login or register a new user. When I try to register a new user, I get denied. The API call is `/auth/register`.
@blcham @Kasmadei Can you check if this also happens to you?
@kostobog could it be because the backend needs a logged user even for public pages? 

This issue is a blocker for #343.

Backend logs:

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/57750426/4e45c31e-6cfb-45e4-b7b1-a70dafea1cf4)

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/57750426/b3b763d5-cef5-478e-98f9-f91e0ea396f2)

**Comment by blcham** [comment]
@LaChope It behaves the same for me, I investigated server log file, and this is the error:

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/4a7ce742-6451-4e0a-b023-a8b6269273fc)

**Comment by kostobog** [comment]
This issue occurs due to a bad login and registration request.
The client sends jsonld with the wrong uri mapped to the username property in the context.

This inconsistency occurred when adjusting fta-fmea to be compatible with keyckloak docker distribution, .
