### ISSUE TITLE
Selection of the system should be disabled when FTA tree/System editor is open

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea-ui#370]
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/57750426/a6387f6b-f254-430b-a144-05e0714b84ff)

A/C:
- [x] selection of system is disabled in FTA editor
- [x] selection of system is disabled in System editor

**Comment by LaChope** [comment]
@blcham FYI

**Comment by blcham** [comment]
Agree I suggest to create two tickets as follows:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/2da72488-9e1c-4788-b521-bf5b094cdcf0)

**Comment by blcham** [comment]
Should be implemented before #378
