### ISSUE TITLE
Show ATA code and title of the subsystem of fault tree in fault tree editor

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#373]
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/b1a8abb4-f24f-4754-a4ce-031efa5972de)

**Comment by blcham** [comment]
Not sure if we will have title --- most-likely we will have to join multiple titles/labels into something like rdfs:comment as titles are not unique per SNS

**Comment by blcham** [comment]
works
