### ISSUE TITLE
List of reusable event types when creating fault event should be filtered according to fault tree

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#374]
@blcham @LaChope 
The list of event types when creating fault event in a fault tree should be filtered as follows:
- the list should not contain the fault tree's root fault event's supertype.
- [optional] the list should be reordered to show SNS failure types of components of the subsystem of the fault tree

### Backend 
Update `FaultEventController.getAllFaultEventsAPI`. The API should take the fault tree fragment as input and filter the list according to it.

### Frontend
Rewrite client to use new version of API

**Comment by blcham** [comment]
@kostobog I do not consider reordering worth the effort as user can search according to ATA code that he can see at root FHA event ... I think alphanumeric ordering is best here while such feature i would implement rather through a taxonomy while having there some artificial not-selectable nodes such as:
- `SNS-based event related to subsystems of $ATA` 
- `FHA-based event related to subsystems of $ATA`

**Comment by kostobog** [comment]
@blcham 
Regarding your comment on distinguishing  SNS and FHA fault events. According to the use-case the label for FHA and SNS follow different naming conventions, e.g. `FC 1.1. ...` for FHA and `21-30-01 ...` for ATA. Also the backend returns a discriminator field `eventType` which will have the value `BASIC` for SNS event types and `INTERMEDIATE` for FHA event types.

**Comment by blcham** [comment]
I agree, i mentioned it multiple times as well, here is new low priority ticket https://github.com/kbss-cvut/fta-fmea-ui/issues/389
