### ISSUE TITLE
Implement play button

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#380]
Implement **play button** for recalculation of failure rate. More information is in #310 

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/63b7530b-3e9c-409a-8413-99a99d9e5dc0)

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/8628c49b-b930-4161-a07c-9740b7e1a3f1)

**Comment by blcham** [comment]
I guess this is being implemented elsewhere.
