### ISSUE TITLE
APP Crush after node select with ReusableFaultEventsProvider

### ISSUE THREAD

**Issue by Kasmadei** [kbss-cvut/fta-fmea-ui#382]
@LaChope Hi. I just noticed that app crushes after i select almost any node with this part:
<img width="692" alt="Screenshot 2024-06-08 at 3 00 01 PM" src="https://github.com/kbss-cvut/fta-fmea-ui/assets/49252228/5001d6f1-e05d-4844-9142-3cb714c5c62f">
Could you check it please ?
Error:
<img width="1051" alt="Screenshot 2024-06-08 at 3 01 05 PM" src="https://github.com/kbss-cvut/fta-fmea-ui/assets/49252228/737e6656-56db-4c66-9bf5-bf6ad2e25f88">

**Comment by Kasmadei** [comment]
@LaChope looks like it some local problem, let me check it first

**Comment by blcham** [comment]
What is state of this?

**Comment by Kasmadei** [comment]
@blcham  It was fixed. I close this issue. Works without problems now 👍
