### ISSUE TITLE
It is possible to create FTA tree with same root node

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#406]
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/46070817-f8bc-42a3-9a31-c3096a55305a)

A/C:
- [ ] backend API is implemented and it is described here how to use it (@kostobog)
- [ ] frontend works as expected (@LaChope)

**Comment by LaChope** [comment]
Anisigning myself, should be done on the backend.

**Comment by kostobog** [comment]
@blcham @LaChope 
PR kbss-cvut/fta-fmea#139 fixes this issue. No need for client side change.
