### ISSUE TITLE
Add additional failure rate

### ISSUE THREAD

**Issue by Kasmadei** [kbss-cvut/fta-fmea-ui#409]
<img width="816" alt="Screenshot 2024-06-12 at 6 07 58 PM" src="https://github.com/kbss-cvut/fta-fmea-ui/assets/49252228/dbfe24db-c9b3-4f06-b26d-f919394c333a">

**Comment by blcham** [comment]
I think the correct way to go is to rename snsManuallyDefinedFailureRate --> basicManuallyDefinedFailureRate

**Comment by blcham** [comment]
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/90de4745-b094-4533-809f-5ae7d8524520)
