### ISSUE TITLE
Cannot open link if not logged in

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#41]
The link https://kbss.felk.cvut.cz/fta-fmea-demo/fta/instance-1287330450 does not work (I get 404 but instead it should redirect me to login page).

See how termit-ui works :).

**Comment by Matthew-Kulich** [comment]
I can't find the problem. I checked apache settings, jenkins and also frontend, but everything seems good. Maybe you can give me a hint, please. @blcham

**Comment by Matthew-Kulich** [comment]
Yes, it works

**Comment by blcham** [comment]
So then it must be apache2 settings ...

**Comment by blcham** [comment]
Not sure now if you fixed it. If not you can try:
- if it works locally on the kbss server, i.e. use something like http://localhost:8080/fta/instance-1287330450
- look to the jenkins termit-ui how it is deployed and how is your deployment different
