### ISSUE TITLE
Add label indicating type of failure rate.

### ISSUE THREAD

**Issue by Kasmadei** [kbss-cvut/fta-fmea-ui#410]
<img width="815" alt="Screenshot 2024-06-12 at 6 08 53 PM" src="https://github.com/kbss-cvut/fta-fmea-ui/assets/49252228/5a7c8342-ab89-47a4-9f64-1a372e3c2830">

Resolves comment: https://github.com/kbss-cvut/fta-fmea-ui/pull/367#discussion_r1633867719

**Comment by blcham** [comment]
@Kasmadei I modified the description to add link

**Comment by blcham** [comment]
Already resolved by https://github.com/kbss-cvut/fta-fmea-ui/pull/411
