### ISSUE TITLE
Check schematicDesignations parsing works well

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#414]
@Kasmadei I thought you said utils.asArray is not possible to use on strings here so I suggested to change the method by copying it from another project, see https://github.com/kbss-cvut/fta-fmea-ui/issues/361#issuecomment-2153651337

_Originally posted by @blcham in https://github.com/kbss-cvut/fta-fmea-ui/pull/413#discussion_r1637860790_

**Comment by Kasmadei** [comment]
Fix: https://github.com/kbss-cvut/fta-fmea-ui/issues/414
