### ISSUE TITLE
It is possible to remove system selection even if it is disabled

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#415]
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/a0287999-6c4d-40f3-ae18-0a1e7a2dc972)

**Comment by Kasmadei** [comment]
Fix: https://github.com/kbss-cvut/fta-fmea-ui/pull/445

**Comment by Kasmadei** [comment]
Fixed.
