### ISSUE TITLE
Harmonize UI when editing events

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea-ui#417]
The merge of #396 and #367 led to inconsistent UI when editing nodes.

- [x] @Kasmadei  For basic nodes, there are now 2 ways to edit the failure rate (we want only the radio, not input field) (also described in https://github.com/kbss-cvut/fta-fmea-ui/issues/451)
- [x] @LaChope The save button should be after the radio options (right now it is in between failure rate field and radio options)
- [x] @LaChope Open for discussion, but the "Description" field does not look nice at all to me

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/57750426/e8beb552-8639-4a41-9e18-ed1e9ec7aa77)

@blcham

**Comment by Kasmadei** [comment]
First point: https://github.com/kbss-cvut/fta-fmea-ui/pull/463

**Comment by blcham** [comment]
Current state:
![image](https://github.com/user-attachments/assets/5d0c60d0-cf8a-4cf0-9c91-36ac2b755122)

**Comment by grotskat** [comment]
@blcham 
- SNS node is OK
- Root node is still the same (2x Event name, SAVE and separator behaviors strange + calculated failure rate is under the separator)
![image](https://github.com/user-attachments/assets/d4592b66-3c9d-4c33-b148-bb7a961a8fd4)

**Comment by blcham** [comment]
We agreed to have SAVE/DISCARD button above separator which is right below failure rates.

**Comment by grotskat** [comment]
It works.
