### ISSUE TITLE
Creating new nodes is broken

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea-ui#424]
After investigation, it seems the issue comes from around this commit: https://github.com/kbss-cvut/fta-fmea-ui/commit/60ea1ddb763c4514ab8b193d8ccff74d9c7e0c6b (on this commit, the issue is reproducible).

This issue is reproducible from the main branch, but not prior to https://github.com/kbss-cvut/fta-fmea-ui/commit/172b1fd1379bd0bbb5265a9c27fb1738aab369a5 (`add-operational-hours` branch).

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/57750426/2ac95175-6d02-48de-8d10-c45b0e1491fa)

**Comment by LaChope** [comment]
@blcham @Kasmadei

**Comment by Kasmadei** [comment]
Fix for this is here: https://github.com/kbss-cvut/fta-fmea-ui/pull/430
