### ISSUE TITLE
External/basic event should not have gate selection

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea-ui#436]
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/57750426/8d621c8e-faac-478b-b336-078190c697b2)

**Comment by blcham** [comment]
Or we can say -- only intermediate nodes should have gate selections. I.e. only if we are creating "new events" in the dialog.

**Comment by LaChope** [comment]
Resolved by #523
