### ISSUE TITLE
Event field is populated with previous selection

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#446]
When I create New fault tree, in field Event is previous selection. This also happens when adding new event to the tree.

- A/C:
- [x] previous selection is not shown when creating a new tree
- [x] previous selection is not shown when adding a new event to an existing tree

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/8de23b72-826f-4fff-8c7d-0211bd651f6f)

**Comment by blcham** [comment]
less priority now.

**Comment by grotskat** [comment]
It is the same for "Create event"
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/a6e95038-1ffe-4973-b436-cd6299061583)

**Comment by grotskat** [comment]
For creating new event it works, but for creating new fault tree it is still prefilled.
