### ISSUE TITLE
FTA event type - different list in tool an Figma

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#447]
Different list of FTA event type in tool and in Figma.
FTA Tool:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/a82fc91a-2a26-4954-8677-75e542e69c4a)

Figma:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/98f72e08-0301-4244-8678-c7fc297ec08c)

**Comment by blcham** [comment]
@grotskat specify where it is happening, maybe part of the issue will be solved in https://github.com/kbss-cvut/fta-fmea-ui/issues/440

**Comment by grotskat** [comment]
> @grotskat specify where it is happening, maybe part of the issue will be solved in #440

A different taxonomy is used. It is used everywhere in the tool because it was the same in the MŠMT project. With Aero, however, different terms of events were defined, which are in the second (Figma) figure.

Example: in tool "External", in Figma it is "Basic referenced event"

**Comment by blcham** [comment]
We need to remove:
Conditional and most-likely Undeveloped too

**Comment by blcham** [comment]
![architecture](https://github.com/user-attachments/assets/029d4fcf-a7e3-43d9-8433-33c54431a852)
