### ISSUE TITLE
It is not possible to change the Gate type in fault tree for "intermediate"

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#448]
Figure shows situation after pressing Save button:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/204fbd2f-b0e5-487a-b169-8b20f71a5c7c)

**Comment by blcham** [comment]
Will be solved by #433.

**Comment by LaChope** [comment]
Resolved by #523
