### ISSUE TITLE
Manually defined failure rate for BASIC node

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#451]
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/e1f9f715-e798-44f6-8fb5-91016e31254c)

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/22cdbf66-ec22-4030-9b78-90797635cc54)

**Comment by blcham** [comment]
Duplicate for #417
