### ISSUE TITLE
Failure rates in the fault tree/right panel are missing

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#453]
**Failure rate values ​​are not displayed in the fault tree.**

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/b7a334df-e0d1-4ff5-aef8-5e03fa2fc541)

**The calculated failure rate for INTERMEDIATE and EXTERNAL nodes and the operational failure rate for BASIC (SNS) are not mentioned in the right panel.**

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/53b8690f-aae9-4a49-b8a9-ee1deb04c9b5)

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/4f47b02f-85c4-4144-a5ee-a1092155ac2f)

**Comment by blcham** [comment]
- Calculate failure rate should be shown there only if the tree was evaluated
- Operational failure rate should be shown there only if it exists, i will check

**Comment by blcham** [comment]
> * Calculate failure rate should be shown there only if the tree was evaluated

@grotskat update description of this issue if it makes sense to you

**Comment by grotskat** [comment]
resolved
