### ISSUE TITLE
Switching radio button strangely changes event

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#456]
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/46d1a403-72f8-4fa0-8bb9-62cfca8cda66)

**Comment by blcham** [comment]
FYI @grotskat

**Comment by Kasmadei** [comment]
@blcham Having clicked through all the options, I didn't see the node name changing, but I noticed that this needs to be added: akaene:fix/switching-radio-button

**Comment by Kasmadei** [comment]
@LaChope Hi Max, have you noticed this strange behavior?

**Comment by Kasmadei** [comment]
@blcham  Upd. Now i see this problem. I'll try to fix it

**Comment by LaChope** [comment]
@Kasmadei Yes I noticed the same behaviour than blcham described.

**Comment by blcham** [comment]
Closing as it is duplicate for #484
