### ISSUE TITLE
Fix generation of partial FMEA table from FTA

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#46]
Fix the generation of FMEA table from a fault tree. The procedure processes each tree path, i.e. fault events from the leaf failure event (e.g. basic failure event) to root failure event in the FT. The procedure should first select the **Function** and then derive **Component**, **Failure Mode** and **local, final and intermediate effects**.
 
- select **Function** - select function (F) in a function failure (FF) fault event  closest to the path's leaf
- select **Component** - select the component (C) of the selected function F
- select **Failure Mode** - select the Failure Mode (FM) of the Fault Event which is a direct child of the FF Fault Event . If there is no child fault event or if the fault event is not a manifestation of a failure mode leave the failure mode column empty.
- select **Cause** - select the FailureModeCause (FMC) is either the direct required FailureModeCause of the selected FM or the direct FailureModeCause impairing the selected F. Each possible cause FMC that can be selected should be used in a new FMEA row.
- select **Local Effect** - the local effect (LE) should be a direct parent of the FF fault event and it should be a failure of a function which is different from function F and is in component C. If there is no such fault event leave the column empty.
- select **Final Effect** (no changes in requirements) - select the final effect EF as the root fault event in the path
- select **Intermediate Effects** - all fault events in the same order as events in the path between the LE and EF excluding both LE and EF. If LE is not selected/empty start from FF instead.

Finally make sure that the each generated row in the table is unique.

**Comment by Matthew-Kulich** [comment]
- Do we presume that every Function and Failure mode will always have assigned a Component (in generation partial FMEA)? Atm Component can be null.
- There can be a case when Failure mode is not assigned to Functions. Do we presume that Failure mode will be always be assigned? In case it wont, do we want to notify user ?
@kostobog

**Comment by kostobog** [comment]
> * Do we presume that every Function and Failure mode will always have assigned a Component (in generation partial FMEA)? Atm Component can be null.

For now it is possible to have behavior without a component.

> * There can be a case when Failure mode is not assigned to Functions. Do we presume that Failure mode will be always be assigned? In case it wont, do we want to notify user ?

For now it is possible to have Function without a FailureMode.

**Comment by Matthew-Kulich** [comment]
If we have this situation and function F2 has FailureMode type Cause. How should it look like ?
![image](https://user-images.githubusercontent.com/67843655/169988174-a614eec4-3b14-4558-97ed-76b651b5767d.png)

Like this without cause? 
![image](https://user-images.githubusercontent.com/67843655/169988657-95440f7b-f83c-4d6c-b5fa-b46c8acabf5d.png)

@kostobog

**Comment by kostobog** [comment]
Good question. Simple answer is that in this case the FMEA the cause for F2 
should be in the cause column and the failure mode column should be empty. 
Component | Function | Cause        | Failure Mode |   Local Effect |  ... | Final Effect 
  qeyh5yh    |  F2          |  FM-cause  |         -            |                      |      |  F1 fails
 

Regarding the second question I added another bullet in the feature description.

**Comment by Matthew-Kulich** [comment]
Ok, thanks
