### ISSUE TITLE
Small issues in FTA tree

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#469]
- [x] manually defined failure rate issue

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/a3fed26e-d094-4e67-9c61-961826bc1a3b)

- [x] disabling edit of FTA nodes
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/a93c63f3-9d13-4a0f-9960-ba445c6a6dd5)

- [x] radio button should not be on simple basic node
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/09ab1853-a783-447c-accc-9b40fe145463) 

- [x]  read-only value should be properly visualized
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/4b4015d4-11b1-45c8-bdb5-70f9c6525110)

**Comment by Kasmadei** [comment]
@blcham As I mentioned, it looks like the issue with the double-click is related to the node. The node http://onto.fel.cvut.cz/ontologies/fta-fmea-application/fault-event/instance1204570762 (which should be clickable) has the property "isReference: true", but it lacks the references.isPartOf property, which is necessary to enable the double-click functionality.

**Comment by Kasmadei** [comment]
@blcham  Fix for point number 3: https://github.com/kbss-cvut/fta-fmea-ui/pull/477

**Comment by kostobog** [comment]
@blcham @Kasmadei 
Regarding issue with double-click on external reference node. For me it works with current version in main. It works in docker as well. The `isPartof` property is populated.
