### ISSUE TITLE
It should be possible to change GATE of intermediate node

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#474]
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/4a00c8bd-7d94-467a-a891-406a9a657998)

**Comment by Kasmadei** [comment]
Fix: https://github.com/kbss-cvut/fta-fmea-ui/pull/502

**Comment by blcham** [comment]
Fixed by https://github.com/kbss-cvut/fta-fmea-ui/pull/512/files#r1672954391.
