### ISSUE TITLE
Last editor value is not shown within FTA trees table

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#478]
Not sure, but maybe it happens only after I modify the FTA tree ?!

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/f5ec8250-40cb-4287-96d0-17edbab5e49b)

**Comment by kostobog** [comment]
@blcham 
A PR for this issue is blocked by PR #546 fixing #365
