### ISSUE TITLE
[L] "Gate Type" dropdown menu is missing during New fault tree creation

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#491]
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/571c361b-9ccc-4a74-ab14-808393b24103)

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/517cc68a-fc3f-4103-b62c-ce9667c86e18)

**Comment by LaChope** [comment]
Resolved by #523
