### ISSUE TITLE
Operational failure rate calculated during fault tree evaluation is not visible in fault event editor

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#492]
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/18463762/9404d620-b63a-4859-baf0-80327c3f5a96)

- [x] Backend should - fixed by kbss-cvut/fta-fmea#132
  - store evaluated operational failure rate in `ATASystem.failureRate.estimate`. ATASystem is found in the array`faultEvent.supertypes.supertypes`.
  - store failure rate and failure rate estimate in dedicated context which is common for all systems to avoid jopa single value property constraint violation exceptions.
- [x] Frontend not showing operational failure - fixed by #493

**Comment by blcham** [comment]
@Kasmadei have a peek

**Comment by blcham** [comment]
@kostobog LGTM, seems like can be closed
