### ISSUE TITLE
Radio button for Manual failure rate is not visible

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea-ui#496]
@kostobog @Kasmadei 

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/57750426/4237f7d0-068f-49e4-b577-a86517ee7e35)

**Comment by LaChope** [comment]
SNS basic node should have failure rate
Not on any other type:
- Simple external
- Simple basic

**Comment by blcham** [comment]
@LaChope  SNS basic node should have a radio-button on the manually-defined failure rate:


But radio button should not be on types:
- Simple external node
- Simple basic node
