### ISSUE TITLE
Strange source code

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#504]
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/4bd21008-f89e-4263-a17d-757df78232ab)

**Comment by blcham** [comment]
I guess this is super-easy task

**Comment by LaChope** [comment]
@blcham do you remember which file is it?

**Comment by blcham** [comment]
You found it :)

**Comment by LaChope** [comment]
@blcham Got it, I removed `setPredictedFailureRate` as it seemed to be the same as `setSnsPredictedFailureRate`. I tested and everything seems to work fine (I created new nodes, changed their failure rate)
