### ISSUE TITLE
Implement filtering of SNS and FHA name within FHA table

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#507]
It should be possible to filter FHA table based on:
- SNS name substring
- FHA name substring

----

The implementation should look like this:
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/d97e1322-668d-45c4-a746-a7a7b7ff621b)

-----

It should be implemented in a similar manner as in RM:
![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/126f1656-2c9b-4efe-989b-fbd9010e82ca)

A/C:
- [ ] @kostobog filtering list of FHA events is implemented on backend (AND operator is among filters)
- [ ] @LaChope filtering is implemented on frontend

**Comment by kostobog** [comment]
@blcham @LaChope 
Fulltext search for fha and sns is implemented in PR kbss-cvut/fta-fmea#141

The api can be used with no parameters:
- `/faultTrees/summaries`

Search, paging and sorting parameters can be used in the same request.

 ### Search Description
Search request parameters:
- `label` - filters by fault tree name which should be the same as the FHA label
- `snsLabel` - filters by the label of system of the top event of the fault tree

Search request Examples:
- find by FHA -  `/faultTrees/summaries?label=FC 1.1`
- find by SNS-  `/faultTrees/summaries?snsLabel=21-30`
- find by FHA and SNS-  `/faultTrees/summaries?label=FC 1.1&snsLabel=21-30`

 ### Paging and Sorting Description
Paging and sort request parameters:
- `page` - index of the retrieved page
- `size` - size of the page
- `sort` - specifies sorting according to a single sort parameter according to the specified direction. 
  - there are three sort parameters:
    - `date` - sorts by date (creating or modified if present)
    - `label` - sorts by fault tree label
    - `snsLabel` - sorts results by label of SNS system of the top event of the fault tree
  - Direction of sorting 
    - ascending - `+` but must be URL encoded `%2B`
    - descending - `-`
 
Paging and Sorting request Examples:
- page using default order - `/faultTrees/summaries?page=2&size=2` 
- page with ordered descending (operator `-`) date - `/faultTrees/summaries?page=2&size=2&sort=-date`
- page with ordered ascending (operator `+`) date - `/faultTrees/summaries?page=2&size=2&sort=%2Bdate` - note that the ascending operator `+` needs to be URL encoded (`%2B`) or it will be interpreted as space.

**Comment by kostobog** [comment]
@blcham 
> filtering list of FHA events is implemented on backend (**AND** operator is among filters)

What is the AND operator in the acceptance criteria ? 

The current implementation will return fault tree summaries that match both FHA and SNS if both are provided.
Is that the expected behavior?

**Comment by blcham** [comment]
> What is the AND operator in the acceptance criteria ?
> 
> The current implementation will return fault tree summaries that match both FHA and SNS if both are provided. Is that the expected behavior?

yes that is exactly what i meant by that
