### ISSUE TITLE
Inconsistent behaviour of BASIC, EXTERNAL, INTERMEDIATE node

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#510]
BASIC, EXTERNAL and INTERMEDIATE node should be somehow similar to fill in but they are not:

![Image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/f10116bb-3469-404d-843a-953adfcd02aa)

**Comment by blcham** [comment]
PHASEs:
=======

1) There is only event name field
2A) SNS node was selected => show BASIC gateway but disabled
2B) External reference node was selected => show External gateway but disabled
2C) New event name was created => Show node-type to choose from External, Basic, Intermediate etc ... 

3C) Intermediate node-type was selected ==> show OR/AND gate

**Comment by blcham** [comment]
- create tree with new event ==> fta event type is not disabled
- intermediate node is missing gate in right panel

**Comment by LaChope** [comment]
> * create tree with new event ==> fta event type is not disabled
> 
> * intermediate node is missing gate in right panel which should be enabled

@blcham Fixed with [d599394](https://github.com/kbss-cvut/fta-fmea-ui/pull/523/commits/d59939485fe779393ef3d0ee70ae84f785ec3a43)
