### ISSUE TITLE
Save and discard button is not hidden when I change back to old value

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#513]
The problem was originally described here: https://github.com/kbss-cvut/fta-fmea-ui/pull/512#issue-2401408883
"""
Open any event with a gate, change the gate without saving (just in the dropdown), then change it back. The Save/Discard buttons are still visible, but the value in the gate dropdown is reset to its initial state. It's unclear why isDirty remains true even after the value has been reverted.
"""

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/e02ff052-46ae-482b-8147-a4fb33f33f9c)

**Comment by LaChope** [comment]
@blcham Is it an issue? Wouldn't it be better to have it always visible and just do nothing if there was no change, and add a notification to user when something is saved/not saved ? IMO, I find it weird to see these buttons appearing and disappearing all the time.

**Comment by LaChope** [comment]
@blcham I close the ticket because I cannot reproduce it anymore, even though I cannot find a specific commit fixing the issue.

**Comment by blcham** [comment]
@grotskat please test well, and create new ticket if the problem occurs again
