### ISSUE TITLE
Filtering events according to the selected event type

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#514]
In the Event field, the user will always see the SNS and FC menu. It should be filtered by event type (EXTERNAL, BASIC, etc.).
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/a8dc907f-cfcb-48a6-925c-f538084bffcc)
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/708459f5-b2cb-4c87-9804-bdce8e564ff6)

**Comment by blcham** [comment]
@grotskat I believe this can be closed as there is event selected first and then gate type is selected.
