### ISSUE TITLE
Move the word "Probability" above the column of numbers

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#516]
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/93380770/608f16e5-d772-4082-801a-98316ecf0956)

**Comment by blcham** [comment]
@grotskat BTW, should it be Probability or Failure rate ?

**Comment by grotskat** [comment]
> @grotskat BTW, should it be Probability or Failure rate ?

@blcham Yes, I think "Failure rate" is correct.

**Comment by grotskat** [comment]
@LaChope CZ: "Intenzita poruch"

**Comment by blcham** [comment]
@grotskat please check it was renamed (@LaChope)

**Comment by LaChope** [comment]
@blcham @grotskat It was not, I realise now I did not do it, will do now.

**Comment by LaChope** [comment]
@blcham @grotskat resolved here: https://github.com/kbss-cvut/fta-fmea-ui/pull/597
