### ISSUE TITLE
Strange behavior of Event name in the right panel

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#529]
If I click on the **Root event** and then another event, it always shows the wrong name. If I click on other events and then back to this one, then it's OK.

![image](https://github.com/user-attachments/assets/3103bd14-4e6f-472d-8f1d-b165fb38c03e)

![image](https://github.com/user-attachments/assets/88e173b6-2049-46ac-9de6-03ec1a462937)

**Comment by blcham** [comment]
Seems to be related to https://github.com/kbss-cvut/fta-fmea-ui/issues/484

**Comment by blcham** [comment]
@grotskat most likely this is solved, please check at KBSS

**Comment by grotskat** [comment]
resolved
