### ISSUE TITLE
Button "Rename" FTA

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#535]
"Rename" doesn't work:
1/ Now we can remove this button.
2/ This button can work later, but only for FTAs with manually created titles, (not for titles selected from FHA list).

![image](https://github.com/user-attachments/assets/660921a6-2f1d-468d-ae32-5a78b029e396)

**Comment by blcham** [comment]
I think more intuitive is to remove.

**Comment by grotskat** [comment]
This already works according to 2/.
