### ISSUE TITLE
Rename button does not work

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#541]
We have alternative 2 options to fix:
- remove the button
- allow renaming the tree only if its root event is not FHA-based 

![Image](https://github.com/user-attachments/assets/b4423d2c-79f3-4dcd-bbd2-e033a65e1503)

**Comment by blcham** [comment]
Implement a harder variant if it takes less than 1,5 hours.

**Comment by kostobog** [comment]
@blcham 
The solution requires changes for existing fault trees. Specifically, for each non FHA based fault tree a triple indicating that the supertype of the root event is not FHA event has to be added. This can be done using the following SPARQL query 
```
PREFIX : <http://onto.fel.cvut.cz/ontologies/fta-fmea-application/>
INSERT {
    GRAPH ?uri{
    	?rootEventType :auxiliary true.
    }
}WHERE {
    GRAPH ?uri{
        ?uri a :fault-tree.
        ?uri :name ?ftName.
        ?uri :is-manifested-by ?rootEvent .
        ?rootEvent :is-derived-from ?rootEventType.
        ?rootEventType a :fha-fault-event.
    }
}
```
