### ISSUE TITLE
Buttons Rename and Delete don't work for Systems

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#556]
@blcham 

- User should be notified with message that he cannot delete the system because there is reference to concrete tree

![image](https://github.com/user-attachments/assets/a9586b8b-ed67-41a6-aca3-41258996c6ca)
![image](https://github.com/user-attachments/assets/faaba578-c710-42a2-83a4-afb069fb13ee)

**Comment by blcham** [comment]
We should either fix or remove options.
