### ISSUE TITLE
No pre-filled default value (min. op. hours) in the specific system

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#558]
![image](https://github.com/user-attachments/assets/7880c017-5ebe-4773-9d04-47d2401a83c9)
![image](https://github.com/user-attachments/assets/3f1e4e4b-0c9e-4fab-a201-eae2f34257a0)

**Comment by blcham** [comment]
Please describe this better.

**Comment by grotskat** [comment]
> @grotskat Please describe this better.

Updated. Ticket divided and edited.
