### ISSUE TITLE
Manually def. failure rate cannot be deleted

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#560]
![image](https://github.com/user-attachments/assets/09dabc94-a22f-48f4-be7e-77376d59f6bd)
![image](https://github.com/user-attachments/assets/0e61c56f-54d3-4d9e-aa53-6f3686ea9280)

**A/C**
- Enable user to set empty failure rate

**Comment by blcham** [comment]
reopen to test.

**Comment by grotskat** [comment]
It works.
