### ISSUE TITLE
User should not be able to delete a system with a fault tree

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#567]
When user deletes a system, the application should:
- [x] delete the system if it has no fault trees
- [x] show warning that it cannot be deleted because it has fault trees

**Comment by grotskat** [comment]
@kostobog 
For newly created systems, everything works.
But systems created earlier (see image below) - cannot be renamed or deleted.
![image](https://github.com/user-attachments/assets/b9231446-3981-41d4-8377-f2f06d439c0e)
