### ISSUE TITLE
Older trees cannot be renamed, new ones can (non FHA-based trees)

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#576]
![image](https://github.com/user-attachments/assets/adad4b1a-7903-410b-a34c-7ac80205349b)
![image](https://github.com/user-attachments/assets/e08d4065-97fc-4c56-bc0f-1956977050f9)

**Comment by grotskat** [comment]
@kostobog It still doesn't work for older trees, see message below.

![image](https://github.com/user-attachments/assets/ca07af22-2ff4-4788-8bb7-e570ad06a169)
![image](https://github.com/user-attachments/assets/64616775-4094-46ce-906d-f3d93ce26aae)

**Comment by kostobog** [comment]
@grotskat 
For me it works on https://kbss.felk.cvut.cz/ava/fta-tool/fta. Try to refresh the browser tab (`ctrl+R` or `ctrl+F5`) or try in a new incognito/private browser window.
