### ISSUE TITLE
Check if changes in branch feature/function-parts are properly merged in main.

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#59]
It seems that some commits in branch feature/function-parts are not merged in main. 
Commits:
[Feature #17] Allow to add existing function to a component Matej Kulich 2/9/2022 4:25 PM d36b9de5
[Feature #15 and #17] Add existing function to a component, fix bug with bad assign Matej Kulich 2/3/2022 1:31 PM 14d0f026
[Feature #11] Add required functions highlighting Matej Kulich 1/27/2022 7:01 PM df2b1ca1
[ Feature #12 ] Add managing function parts Matej Kulich 1/25/2022 9:30 PM 47458028

Check if the changes in those commits are implemented in main. 
If changes are not found in main, merge and resolve conflicts for the changes from those commits into main. 
If changes are found in main: specify the commits in main where the changes are implemented.

**Comment by Matthew-Kulich** [comment]
It is all implemented in 45405263, but it looks like it is not because i just copy pasted code. (I didnt know how to properly merge those two branches with commits).
