### ISSUE TITLE
The refresh button behaves strangely in fault trees

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#593]
The refresh button is behaving strangely: 

- For some fault trees it does nothing when pressed, 
- and for some trees it will change to the previous filled value (from 300 to 100, for example).

- **For some fault trees it does nothing when pressed,** 

![image](https://github.com/user-attachments/assets/968af8a2-5e7e-401f-9620-bc2c797973fc)
![image](https://github.com/user-attachments/assets/ba81ad75-a581-47a5-bc5e-1e3977e3fdb8)
![image](https://github.com/user-attachments/assets/aa511c9e-7d45-4c5b-b275-56aa6977dccd)
![image](https://github.com/user-attachments/assets/a34f527d-dc1b-4863-a3cc-10a4b897b58d)

- **and for some trees it will change to the previous filled value (from 300 to 100, for example).**

![image](https://github.com/user-attachments/assets/96b595d2-8d89-4936-80e7-e574e16f54aa)
![image](https://github.com/user-attachments/assets/c15ea86e-1996-4f22-989c-84fcddf9b7d0)
![image](https://github.com/user-attachments/assets/f98629f4-82b2-429a-a015-2cf96e408994)
![image](https://github.com/user-attachments/assets/4d75f632-061c-482f-9bcf-d754d07745bc)

**Comment by blcham** [comment]
Could you be more specific? How to simulate the issue (on what trees should i click)?

**Comment by grotskat** [comment]
@blcham I added examples.

**Comment by kostobog** [comment]
![Image](https://github.com/user-attachments/assets/513e30d6-2d82-47b8-bfd4-81ba2dcb6667)

**Comment by blcham** [comment]
@grotskat reopening this issue just to test it properly. Please have a look at how it should work as explained in this PR:
https://github.com/kbss-cvut/fta-fmea-ui/pull/626

If you have any suggestions on how to make it better, write It here please . Otherwise, let's close this issue if it works correctly.

**Comment by grotskat** [comment]
It works correctly and it makes sense to me.
@blcham
