### ISSUE TITLE
Remove or disable parts that does not work

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#603]
Revise "typ hradla" and "typ FTA udalosti"

![Image](https://github.com/user-attachments/assets/970f1464-93c4-485f-ae50-a4c9935e661e)

Implement configuration parameter to hide FMEA functionality.

![Image](https://github.com/user-attachments/assets/ba69cda4-b397-4216-8602-426e8dcd965f)

![Image](https://github.com/user-attachments/assets/66ce9c81-6ee4-4394-aca9-deb96827cdc8)

**Comment by kostobog** [comment]
@blcham 
Adding requirement to issue description.

**Comment by blcham** [comment]
@kostobog waiting for answer in PR

**Comment by blcham** [comment]
Need to check at KBSS.

**Comment by blcham** [comment]
tested.
