### ISSUE TITLE
Show message of successful evaluation of FTA tree

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#623]
![Image](https://github.com/user-attachments/assets/03accebd-25e6-4c4b-ab41-f70fe0b48fae)

**Comment by blcham** [comment]
How about:
```
Cutsets of this fault tree were successfully calculated.
```

**Comment by blcham** [comment]
@grotskat please put better suggestion of message as well as translation to czech.

**Comment by grotskat** [comment]
@blcham 
The failure rate was successfully calculated.
Intenzita poruch byla úspěšně vypočtena.
