### ISSUE TITLE
Show tooltips for existing icons

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#624]
![Image](https://github.com/user-attachments/assets/f53df811-07c1-4b46-8b39-2b07ece9ca0c)
![Image](https://github.com/user-attachments/assets/01d5094b-05db-4d15-bdc6-cbbc3ef9e966)

**Comment by blcham** [comment]
@grotskat please provide all 6 descriptions + their czech translations.

**Comment by grotskat** [comment]
**For fault trees:**
EN: Automatic arrangement of the fault tree
CZ: Automatické uspořádání stromu poruch

EN: Export current view
CZ: Exportovat aktuální zobrazení

EN: Recalculate failure rate after changing the value of min. operational hours or failure rates in the fault tree
CZ: Přepočítat intenzitu poruch po změně hodnoty min. provozních hodin nebo intenzit poruch ve stromu poruch

EN: Reset the min. operational hours value
CZ: Resetovat hodnotu min. provozních hodin

**For systems**:
EN: Change the system min. operational hours value
CZ: Změnit hodnotu min. provozních hodin systému

EN: Reset the system min. operational hours value to 200
CZ: Resetovat hodnotu min. provozních hodin systému na 200
