### ISSUE TITLE
Event details section title in create fault tree dialog has blue background color

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#632]
@blcham 
PR #631 introduced a side effect in the style of the `Event Details` title bar in create fault tree and create fault event dialogs. 

![Image](https://github.com/user-attachments/assets/67407fb0-356d-457f-8a4e-f1437785eb86)

![Image](https://github.com/user-attachments/assets/17a0aa7d-b078-492d-9bad-ff35f5bf32ac)

 
Possible solutions are:
1) remove `Event Details` in both create fault tree and create fault event dialogs
2) Remove the background color from `Event Details` title bar in both create fault tree and create fault event dialogs

**Comment by blcham** [comment]
@blcham will close if it looks ok on KBSS

**Comment by blcham** [comment]
looks nice, closing.
