### ISSUE TITLE
Wrong label and description of calculated failure rate at the INTERMEDIATE node

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#633]
EN: Calculated failure rate
CS: Vypočtená intenzita poruch

![image](https://github.com/user-attachments/assets/a65ff71b-1248-46fa-801f-5fb79ab94efd)
![image](https://github.com/user-attachments/assets/8a708b32-1401-4763-a980-ace6adfd9780)

**Comment by blcham** [comment]
@grotskat it is little strange title for this issue .. I renamed it, just check if we mean the same.

**Comment by grotskat** [comment]
It works.
