### ISSUE TITLE
It is not possible to save Manually def. failure rate for External events

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#639]
@blcham 
Pro External event není možné uložit Manual failure rate. Po vyplnění hodnoty a pokusu o uložení se sice ukáže „Event updated“, ale zadaná hodnota zmizí.
![image](https://github.com/user-attachments/assets/006a4290-6ae6-4ff5-b380-9f5a953ff672)
![image](https://github.com/user-attachments/assets/ed7e05e5-1f68-4da8-94eb-aef095d3572b)

**Comment by kostobog** [comment]
@grotskat 
Tested on `FC_12.27. Úplná ztráta indikace vysunutí podvozku: Indikace polohy podvozku + mechanický ukazatel podvozku` A1

**Comment by grotskat** [comment]
It works.
