### ISSUE TITLE
One "FHA based failure rate" has an extra orange number "2"

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/fta-fmea-ui#644]
![image](https://github.com/user-attachments/assets/f4158569-c761-4563-8b11-a3567132ca22)

![image](https://github.com/user-attachments/assets/e87977e7-58dc-41c5-9f01-5bf0d4d4dde1)

**Comment by blcham** [comment]
@grotskat reopening to check kbss and close if it works ok

**Comment by grotskat** [comment]
https://github.com/user-attachments/assets/46cea6de-0ed4-4a10-9874-321b9ccfc94c

**Comment by kostobog** [comment]
@grotskat 
Please check again. It should be fixed.

**Comment by blcham** [comment]
@kostobog tried it and it works
