### ISSUE TITLE
Add hint for possibly outdated values of operational failure rate

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#661]
The operational failure rate could be possibly outdated without the user being able to recognize it.

![Image](https://github.com/user-attachments/assets/105e824b-da09-439b-9b87-ee92469ac051)

Moreover, there are 2 places where this can be stated:
- next to the operational failure rate hint
- next to the play button (="recalculate failure rate")

I suggest to mention it in both places.

![Image](https://github.com/user-attachments/assets/0828ff41-b201-4d49-8f3c-1c2e5330019a)

**Comment by blcham** [comment]
@kostobog please suggest the changes which would @grotskat review

**Comment by grotskat** [comment]
@kostobog @blcham 
"or" is missing in the Play button's EN description, so it is not clear

![image](https://github.com/user-attachments/assets/1790111e-c6f4-4e0d-96ff-a838c5edd777)
![image](https://github.com/user-attachments/assets/6011716c-26c1-4036-b629-b38fdd2a0014)

**Comment by blcham** [comment]
> @kostobog @blcham "or" is missing in the Play button's EN description, so it is not clear

Fixed in https://github.com/kbss-cvut/fta-fmea-ui/commit/7cf570c9dbdd09095a73495922befa38e736a20d
