### ISSUE TITLE
Users should be able to specify failure mode type

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#70]
In System editor when editing failure modes of component as well as when creating failure modes for components the user should be able to specify a Failure Mode Type with two possible options:
- **Failure Mode**
- **Failure Mode Cause**

### Client Requirements
- When the user selects **Failure Mode** option, the original form of failure modes should be shown.
- When the user selects **Failure Mode Cause** option, the form should reduced by removing the behavior type and the required failure modes fields. If the edited failure mode has specified values for child and required failure modes, the user should be notified that they will be removed from the edited failure mode. If the user accepts the change the application should remove child and required failure modes from the edited failure mode and set its behavior type to basic.

The user interface should look as shown in the screenshot below.
![image](https://user-images.githubusercontent.com/18463762/168262745-0525001c-9a75-49c6-ade9-cce9616814ea.png)

### Server Requirements
- model - Implement the Failure Mode Type in Failure Mode entity similar to Behavior Type. 
- FTA generation - do not generate fault events for Failure Modes with a **Failure Mode Cause** value for the Failure Mode Type property.

**Comment by Matthew-Kulich** [comment]
Implemented in #71
