### ISSUE TITLE
Dockerization of fta-fmea tool

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#72]
A/C:
- both UI and backend has their own docker packages published on github, which is triggered by github actions on commit to master/main
- there is docker-compose file in this repository which orchestrates backend and frontend together

Inspiration:
- [csat-planning](https://github.com/kbss-cvut/csat-planning/)
- [SPipes Editor](https://github.com/kbss-cvut/s-pipes-editor/)
- [Termit UI](https://github.com/kbss-cvut/termit-ui/)
- [Termit docker](https://github.com/kbss-cvut/termit-docker/)

**Comment by Matthew-Kulich** [comment]
I will create new pull request for this. This is kinda messy

**Comment by blcham** [comment]
ok
