### ISSUE TITLE
User should be able to edit the Mitigation column in the FMEA table

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#79]
Make the Mitigation column in the FMEA table editable.
User should be able to create, edit and delete mitigations on each row.
One table row has at most one mitigation and one mitigation is associated with at most one row.

The mitigation form should include the following fields:
- title - one line text (use model Mitigation.name)
- description - multiline text (use model Mitigation.description)
- (C) failure mode: user can select the cause or failure mode of the same row as the edited mitigation (use model Mitigation.impairedBehaviors)

**Comment by blcham** [comment]
works.
