### ISSUE TITLE
Fix Failure Mode Dialog in FTA Fault Event editor

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#88]
The dialog fails with browser exception.

The dialog should only allow user to:
- set the failure mode, 
- (C) show (if set) and change the component of the failure mode - this is nice to have. Leave it for later if it takes too much time.
- show (if set) and change the mitigation of the failure mode 
The rest of the steps should be removed.

**Comment by Matthew-Kulich** [comment]
"set the failure mode" > set from existing failure modes or also can create new failure mode ? @kostobog
